### ISSUE TITLE
Add dependency on IPC::System::Simple

### ISSUE THREAD

**Issue by cxw42** [barefootcoder/leadpipe#1]
I just saw this in metacpan/recent, and it looks very interesting!  One thing that jumps out at me: please `use IPC::System::Simple` or otherwise add it as a dependency. `use autodie ':all'` fails on systems without IPC::System::Simple ([example in one of my recent releases](http://analysis.cpantesters.org/reports_by_field?distv=App-unbelievable-v0.0.2-TRIAL;field=qr%3A%28Can%27t%20locate%20%5CS%2Bpm%29)).  Thanks!

**Comment by barefootcoder** [comment]
Yep, good call; I knew that once upon a time but had forgotten it here. :-)  Will release 0.01_02 later tonight.

**Comment by barefootcoder** [comment]
That should do it; if you can, install the latest dev version (0.01_02) and let me know if that clears it up for you.

**Comment by cxw42** [comment]
Looks good to me!  Thanks!
