### ISSUE TITLE
Test failures because of localized error messages

### ISSUE THREAD

**Issue by eserte** [barefootcoder/leadpipe#2]
On some systems (i.e. perl <= 5.20 and non-English locale) the test suite fails:
```
...
    #   Failed test 'good error'
    #   at t/errors.t line 299.
    #          got: 'bad_file_write: file read/write failure [Can't open '/cant/possibly/exist' for writing: 'Datei oder Verzeichnis nicht gefunden']
    # '
    #     expected: 'bad_file_write: file read/write failure [Can't open '/cant/possibly/exist' for writing: 'No such file or directory']
    # '
    # Looks like you failed 1 test of 2.

#   Failed test 'catches failures in file ops'
#   at t/errors.t line 299.
# Looks like you failed 1 test of 22.
t/errors.t ..... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/22 subtests 
t/export.t ..... ok

    #   Failed test 'good error pattern'
    #   at t/flow-guts.t line 91.
    #                   'Can't open($fh, '/this/file/cannot/possibly/exist'): Datei oder Verzeichnis nicht gefunden at /var/tmp/cpansmoker-1023/2020020405/MascgC5qVO/test_autodie line 3
    # '
    #     doesn't match '(?^:No such file or directory)'
    # Looks like you failed 1 test of 2.

#   Failed test 'autodie is turned on'
#   at t/flow-guts.t line 91.
# Looks like you failed 1 test of 8.
t/flow-guts.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/8 subtests 
...
```

**Comment by barefootcoder** [comment]
Shit. :-/  Yeah, I caught the exit value being different fairly quickly, but I forgot about the language issue.  So, I believe I'm working around a similar issue in Date::Easy via forcing `C` locale ... do you think that's the best solution here as well? or should I just make much more liberal regexen?  If you have an opinion, I'd certainly love to hear your thoughts. :-)

**Comment by barefootcoder** [comment]
Sorry; it wasn't Date::Easy where I had done this, but rather PerlX::bash.  Which is even closer to this than the date stuff, so I'm hopeful that this will fix it, although I didn't have any luck reproducing the error on my system.  But we shall see, I suppose. :-)

**Comment by eserte** [comment]
A possible solution is to get the localized error messages, and use them in the tests. I do this in my Doit testsuite, see
* https://github.com/eserte/Doit/blob/23ee1e748985f0a49f7db1a3e663c6203654d61b/t/doit.t#L32-L38
* https://github.com/eserte/Doit/blob/23ee1e748985f0a49f7db1a3e663c6203654d61b/t/doit.t#L55

**Comment by barefootcoder** [comment]
> A possible solution is to get the localized error messages, and use them in the tests.

Yeah, that's a good call, and a handy technique.  I will totally try that out.

**Comment by barefootcoder** [comment]
Okay, I think this is all fixed as well.  I'm closing it out; reopen if you see any more similar issues.

Hopefully 0.02 is coming in the next couple of days.
