### ISSUE TITLE
META.json lists barefootcoder/pb

### ISSUE THREAD

**Issue by cxw42** [barefootcoder/leadpipe#3]
At <https://metacpan.org/source/BAREFOOT/Pb-0.01_02/META.json#L82>, the bugtracker URL is listed as `...barefootcoder/pb` rather than `...barefootcoder/leadpipe`.  As a result, the autolinked GitHub issues [on the release-description page](https://metacpan.org/release/BAREFOOT/Pb-0.01_02) are 404s ;) .

**Comment by barefootcoder** [comment]
You know, I totally fixed that, but only on one of my machines. :-/  I shall try try again ...

**Comment by barefootcoder** [comment]
Okay, looks like 0.01_03 fixes it, so I'm closing this out for now.  But let's keep a close eye on it. ;->

Hopefully I'll get to release 0.02 tomorrow or Monday.
